version: '3'
services:
  web:
    image: nginx:latest
    restart: on-failure
    ports:
     - ${APP_PORT}:80
    volumes:
        - .:/application  
        - ./site.conf:/etc/nginx/conf.d/default.conf      
    links:
      - app
  app:
    build: .
    restart: on-failure
    environment:      
      DB_CONNECTION: ${DB_CONNECTION}
      DB_DATABASE: ${DB_DATABASE}
      APP_NAME: ${APP_NAME}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}     
      PORT: ${APP_PORT}
    volumes:
      - .:/application          
networks:
  default:
    driver: bridge