version: '3'
services:
  web:
    image: nginx:latest
    restart: on-failure
    ports:
     - "9001:80"
    volumes:
        - ./api:/application  
        - ./site.conf:/etc/nginx/conf.d/default.conf      
    links:
      - app
  app:
    build: ./api
    restart: on-failure
    environment:
      DEBUG: 'false'
      DB_CONNECTION: sqlite
    volumes:
      - ./api:/application          
networks:
  default:
    driver: bridge